#!/usr/bin/env bash
# redirect
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i '/server _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default
sudo service nginx start
