#!/usr/bin/env bash
# custom 404 page
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
sudo sed -i '/server_name _/a error_page 404 /custom_404.html; location = /custom_404.html {root /var/www/html/; internal; }' /etc/nginx/sites-available/default
sudo service nginx restart
