#!/usr/bin/env bash
# redirect
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/server _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default
sudo sed -i '/server _/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html; internal; }' /etc/nginx/sites-available/default
sudo service nginx restart
