#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i "$ aENABLED=1" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
echo "
frontend haproxynode
	bind *:80
	mode http
	default_backend backendnodes

backend backendnodes
	balance roundrobin
	server 2377-web-01 34.138.95.175:80 check
	server 2377-web-02 104.196.118.242:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
