#!/usr/bin/env bash
# Make bash version of FizzBuzz
count=1
while [ $count -le 100 ]; do
	if ((count % 15 == 0)); then
		echo "FizzBuzz"
	elif ((count % 5 == 0)); then
		echo "Buzz"
	elif ((count % 3 == 0)); then
		echo "Fizz"
	else
		echo $count
	fi
	((count++))
done
