#!/usr/bin/env bash
#display Holberton School OR Good Luck OR bad luck
count=0
while [ $count -lt 10 ]; do
	if [ $count -eq 4 ]; then
		echo bad luck
	elif [ $count -eq 8 ]; then
		echo good luck
	else
		echo Holberton School
	fi
done
