#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
pkill apache2
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
